---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: podinfo
  namespace: flux-system

spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m

  dependsOn: []

  sourceRef:
    kind: GitRepository
    name: flux-system

  path: ./applications/dev/podinfo
  prune: true
  wait: true

...
