---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease

metadata:
  name: podinfo
  namespace: default

# https://github.com/stefanprodan/podinfo/tree/master/charts/podinfo
spec:
  interval: 30m
  chart:
    spec:
      chart: podinfo
      version: "6.9.0"
      sourceRef:
        kind: HelmRepository
        name: stefanprodan
        namespace: default
  values:
    image:
      repository: ${podinfoRepo}
      tag: 6.8.0 # {"$imagepolicy": "default:podinfo:tag"}

    service:
      enabled: true
      type: NodePort

...
